# @package _global_

dataset:
  # Base search
  search:
    engines:
      dense:
        backend: qdrant
      sparse:
        backend: elasticsearch

  # Train/val splits
  training:
    queries:
      train:
        - identifier: frank_a_en_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            language: en
            what: queries
          split: train
          link: frank_a_sections
      val:
        - identifier: frank_a_en_val
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            language: en
            what: queries
          split: validation
          link: frank_a_sections

    sections:
      sections:
        - identifier: frank_a_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            language: en
            what: sections

  # Benchmarks
  benchmark:
    - queries:
        identifier: frank_a_en_val
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          language: en
          what: queries
        split: validation
      sections:
        identifier: frank_a_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: sections
    - queries:
        identifier: frank_b_en_val
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          language: en
          what: queries
        split: validation
      sections:
        identifier: frank_b_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          language: en
          what: sections