_target_: lightning.fabric.strategies.DeepSpeedStrategy
stage: 3
offload_optimizer: true
offload_parameters: true
partition_activations: false
cpu_checkpointing: true
offload_params_device: nvme
offload_optimizer_device: nvme
nvme_path: ${sys.nvme}
thread_count: 2