defaults:
  - strategy: single_device
  - loggers:
      - csv
  - callbacks:
      - pprint_batch
      - pprint_model_stats
  - _self_

_target_: vod_exps.utils.init_fabric
accelerator: auto
devices: ${resources.n_devices}
precision: 32
