on_init: false
n_max_eval: 1_000
tune_parameters: true
n_tuning_steps: 1_000
parameters:
  faiss: 1.0
  bm25: 1.0
metrics:
  - "ndcg"
  - "mrr@10"
  - "hitrate@01"
  - "hitrate@03"
  - "hitrate@20"
  - "hitrate@100"
  - "recall@50"