defaults:
  - tokenizer: default
  - templates: ${infer_model_type:${model/encoder}}
  - _self_

_target_: raffle_ds_research.core.builders.auto_builder
name: frank
subset_name: A
language: en
subset_size: null
prep_map_kwargs:
  num_proc: ${resources.num_proc}