defaults:
  - tokenizer: default
  - templates: ${infer_model_type:${model/encoder}}
  - dl_sampler: frank
  - _self_

_target_: raffle_ds_research.core.dataset_builders.RetrievalBuilder.from_name
name: frank.A.en.pos
subset_size: null
include_only_positive_sections: true
prep_map_kwargs:
  num_proc: ${resources.num_proc}