# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: ".+/utils.py"
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [ python ]
        args: [ --fix, --exit-non-zero-on-fix ]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]

