pprint_batch:
  _target_: vod_workflows.callbacks.PprintBatch
  training: true
  validation: false
  testing: false
  is_retrieval: true
  tokenizer_encoder: ${tokenizers.encoder}
  log_to_wandb: true
