# @package _global_

defaults:
  - frank-bert-base
  - override /model/encoder: t5-base
  - _self_

batch_size:
  effective: 32
  per_device: 8
  per_device_eval: 8
  per_device_predict: 512

trainer:
  accelerator: gpu
  precision: 32