# @package _global_

defaults:
  - frank-bert-base
  - override /model/encoder: t5-xl
  - _self_

batch_size:
  effective: 32
  per_device: 1
  per_device_eval: 2
  per_device_predict: 256

fabric:
  accelerator: gpu
  precision: bf16-mixed


#collates:
#  train:
#    n_sections: 16
#    max_pos_sections: 4