defaults:
  - encoder: bert-tiny
  - gradients: kl_div
  - optimizer: adamw # todo: lion
  - scheduler: linear
  - monitor: retrieval
  - _self_

_target_: raffle_ds_research.core.ml_models.Ranker
embedding_size: 512
compile: false