defaults:
  - search_defaults: default
  - options: default
  - _self_

# Base search
search:
  engines:
    dense:
      backend: qdrant
    sparse:
      backend: elasticsearch

# Train/val splits
training:
  queries:
    train:
      - identifier: scidocs_train
        name_or_path:
          _target_: vod_datasets.BeirDatasetLoader
          what: queries
        subsets: scidocs
        split: train
        link: scidocs_sections
    val:
      - identifier: scidocs_dev
        name_or_path:
          _target_: vod_datasets.BeirDatasetLoader
          what: queries
        subsets: scidocs
        split: dev
        link: scidocs_sections

  sections:
    sections:
      - identifier: scidocs_sections
        name_or_path:
          _target_: vod_datasets.BeirDatasetLoader
          what: sections
        subsets: scidocs

# Benchmarks
benchmark:
  - queries:
      identifier: scidocs_test
      name_or_path:
        _target_: vod_datasets.BeirDatasetLoader
        what: queries
      subsets: scidocs
      split: test
      link: scidocs_sections

    sections:
      identifier: scidocs_sections
      name_or_path:
        _target_: vod_datasets.BeirDatasetLoader
        what: sections
      subsets: scidocs
