# @package _global_

dataset:
  train:
    - frank.A.en-pos:train
    - squad.en:train
  validation:
    - frank.A.en-pos:val
    - squad.en:val
  benchmark:
    - frank.A.en:val
    - frank.B.en:val

benchmark_search:
  faiss:
    factory: IVFauto,Flat
    nprobe: 64

search:
  faiss:
    factory: IVFauto,Flat
    metric: inner_product
    nprobe: 32


trainer:
  max_steps: 100_000
  period: 10_000
  val_check_interval: 250