# @package _global_

defaults:
  - override /dataset/templates: encode_lang
  - _self_

dataset:
  train:
    - frank.A.en-pos:train
    - frank.A.da-pos:train
    - frank.A.de-pos:train
    - squad.en:train
  validation:
    - frank.A.en-pos:val
    - frank.A.da-pos:val
    - frank.A.de-pos:val
    - squad.en:val
  benchmark:
    - frank.A.en:val
    - frank.A.da:val
    - frank.A.de:val
    - frank.B.en:val
    - frank.B.da:val
    - frank.B.de:val

benchmark_search:
  faiss:
    factory: IVFauto,Flat
    nprobe: 64

search:
  faiss:
    factory: IVFauto,Flat
    metric: inner_product
    nprobe: 32

trainer:
  max_steps: 100_000
  period: 20_000
  val_check_interval: 500
