# @package _global_

dataset:
  train:
    - frank.A.en-pos:train
    - frank.A.da-pos:train
  validation:
    - frank.A.en-pos:val
    - frank.A.da-pos:val
  benchmark:
    - frank.B.en-pos:val
    - frank.B.da-pos:val

benchmark:
  search:
    faiss:
      factory: Flat
      nprobe: 32

search:
  faiss:
    factory: IVFauto,Flat
    metric: inner_product
    nprobe: 32
