# @package _global_

# This config is for 4xA100 GPUs (40GB)

defaults:
  # HF transformer model name
  - override /model/encoder: bert-base
  # Strategy
  - override /fabric/strategy: ddp

resources:
  num_workers: 2
  num_proc: 16
  omp_threads: ${int_div:${n_cpus:},2}

model:
  gradients:
    section_chunk_size: null
  compile_encoder: true
  compile_kwargs:
    dynamic: false
    fullgraph: false

batch_size:
  effective: 32
  per_device: 4
  per_device_eval: 16
  per_device_predict: 1024

collates:
  train:
    n_sections: 48
    max_pos_sections: 12
    prefetch_n_sections: 64

fabric:
  precision: bf16-mixed
  accelerator: gpu
