# @package _global_

# This config is for 4xA100 GPUs (40GB)

defaults:
  - ddp-base
  # HF transformer model name
  - override /model/encoder: bert-large

model:
  gradients:
    section_chunk_size: 6