# @package _global_

# This config is for 4xA100 GPUs (40GB)

defaults:
  # HF transformer model name
  - override /model/encoder: bert-base
  # Strategy
  - override /fabric/strategy: ddp

resources:
  num_workers: 2
  num_proc: 16
  omp_threads: ${int_div:${n_cpus:},2}

model:
  encoder:
    model_config:
      dropout_rate: 0 # default: 0.1
  optimizer:
    lr: 1e-4
    weight_decay: 1e-3
    eps: 1e-8
  gradients:
    section_chunk_size: 24
  compile_encoder: true
  compile_kwargs:
    dynamic: false
    fullgraph: false

batch_size:
  effective: 32
  per_device: 8
  per_device_eval: 8
  per_device_predict: 1024

collates:
  train:
    n_sections: 96
    max_pos_sections: 24
    prefetch_n_sections: 128

fabric:
  precision: bf16-mixed
  accelerator: gpu
