defaults:
  - encoder: bert-tiny
  - gradients: supervised_retrieval
  - optimizer: adamw # todo: lion
  - scheduler: linear
  - monitor: retrieval
  - _self_

_target_: vod_models.Ranker
compile_encoder: false
gradient_checkpointing: false