# @package _global_

defaults:
  - override /model/encoder: bert-tiny
  - _self_

seed: 1

benchmark_search:
  faiss:
    factory: Flat

trainer:
  max_steps: 1000
  period: 300
  val_check_interval: 5
  n_max_eval: 100
  parameters:
    bm25: -1

dataset:
  subset_size: 1_000
  filter_unused_sections: false
  train: frank.A.en-pos:train
  validation: frank.A.en-pos:val
  benchmark:
    - frank.A.en-pos:val

schedule:
  benchmark_on_init: false

batch_size:
  per_device: 2
  per_device_eval: 4
  per_device_predict: 512

resources:
  num_workers: 1
  num_proc: 4

model:
  gradients:
    section_chunk_size: 32

collates:
  train:
    n_sections: 128
    max_pos_sections: 32
    prefetch_n_sections: 256
    in_batch_negatives: true

  eval:
    n_sections: 128
    max_pos_sections: 32
    prefetch_n_sections: 256
