_target_: vod_models.VodBertEncoder.from_pretrained
pretrained_model_name_or_path: bert-base-uncased
pooler:
  _target_: builtins.dict
  projection_size: null
  output_activation: null
  output_norm: null
  agg_method: cls
  scaler: null
