defaults:
  - bert-base
  - _self_

_target_: vod_models.VodXLMRobertaEncoder.from_pretrained
pretrained_model_name_or_path: intfloat/e5-base-v2
pooler:
  agg_method: mean
  output_norm: l2
  scaler: 100
