defaults:
  # Model and tokenizers
  - model: ranker
  - tokenizers: default
  # Dataset and dataloaders
  - datasets: fiqa
  - dataloaders: default
  - collates: default
  - templates: default
  # Training/eval logic
  - fabric: default
  - trainer: default
  - benchmark: default
  # System & resources
  - resources: default
  - batch_size: default
  - sys: default
  - env: default
  - hydra: default

seed: ${global_seed:}
model_name: ${parse_model_name:${model}}
encoder_name: ${parse_encoder_name:${model}}
lm_name: ${parse_lm_name:${model}}
exp_version: "v3.0"
exp_suffix: ""
exp_name: retrieval
run_name: ${fmt_mn:${model_name}}--${rdn_name:}-${exp_version}${exp_suffix}
load_from: null
