_target_: vod_models.VodEncoder.from_pretrained_backbone
name_or_path: bert-base-uncased
backbone_cls: BertModel
pooler_config:
  projection_size: null
  output_norm: null
  output_activation: null
  agg_method: cls
