on_init: false
n_max_eval: null
parameters:
  dense: 1.0
  sparse: 1.0
metrics:
  - "ndcg"
  - "mrr@10"
  - "mrr@100"
  - "hitrate@01"
  - "hitrate@03"
  - "hitrate@10"
  - "hitrate@100"
  - "recall@50"
