defaults:
  - dataset: retrieval
  - dl_sampler: none
  - model: default
  - tokenizer: default
  - trainer: default
  - benchmark: default
  - resources: default
  - batch_size: default
  - fabric: default
  - sys: default
  - hydra: default
  - env: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

seed: ${global_seed:}
model_name: ${model.encoder.pretrained_model_name_or_path}
exp_version: "v2.5"
exp_suffix: ""
exp_name: retrieval
run_name: ${fmt_mn:${model_name}}--${rdn_name:}-${exp_version}${exp_suffix}
load_from: null

dataloaders:
  # Defines the configurations for `torch.utils.data.Dataloader`
  train:
    batch_size: ${batch_size.per_device}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True
  eval:
    batch_size: ${batch_size.per_device_eval}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True
  benchmark:
    batch_size: 16
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True
  predict:
    batch_size: ${batch_size.per_device_predict}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: False

collates:
  # Defines the configurations for `dataset_builder.HfBuilder._collate_config`
  predict:
    query_max_length: 128
    section_max_length: 200
  train:
    # Configuration for the training/evaluation `Collate`
    n_sections: 16
    max_pos_sections: 4
    support_size: 100
    prefetch_n_sections: 300
    post_filter: null
    do_sample: false
    in_batch_negatives: false
    prep_num_proc: ${resources.num_proc}
    query_max_length: ${collates.predict.query_max_length}
    section_max_length:  ${collates.predict.section_max_length}
  benchmark:
    # Configuration for the benchmark eval. `Collate`
    n_sections: null
    max_pos_sections: null
    support_size: null
    prefetch_n_sections: 1000
    post_filter: null
    do_sample: false
    in_batch_negatives: false
    prep_num_proc: ${resources.num_proc}
    query_max_length: ${collates.predict.query_max_length}
    section_max_length:  ${collates.predict.section_max_length}