defaults:
  - builder: retrieval
  - model: default
  - resources: default
  - batch_size: default
  - trainer: default
  - monitor: retrieval
  - sys: default
  - hydra: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

seed: ${global_seed:}
compile: false
model_name: ${model.encoder.pretrained_model_name_or_path}
exp_version: "v1.8"
exp_suffix: ""
exp_name: retrieval
run_name: ${fmt_mn:${model_name}}--${rdn_name:}-${exp_version}${exp_suffix}

benchmark:
  # defines the benchmarks to be run after each training period
  on_init: false
  builders:
    - name: frank.B.en
      splits: [ validation ]
    - name: frank.A.en
      splits: [ validation ]

dataloaders:
  # Defines the configurations for `torch.utils.data.Dataloader`
  train:
    batch_size: ${batch_size.per_device}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True
  eval:
    batch_size: ${batch_size.per_device_eval}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True
  predict:
    batch_size: ${batch_size.per_device_predict}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: False

collates:
  # Defines the configurations for `dataset_builder.HfBuilder._collate_config`
  train:
    # Configuration for the training `Collate`
    n_sections: 16
    max_pos_sections: 4
    prefetch_n_sections: 300
    do_sample: false
    question_max_length: 128
    section_max_length: 200
  eval:
    # Configuration for the eval. `Collate`
    n_sections: 16
    max_pos_sections: 4
    prefetch_n_sections: 300
    do_sample: false
    question_max_length: 128
    section_max_length: 200
  static:
    # Configuration for the static eval. `Collate`
    n_sections: 500
    max_pos_sections: 50
    prefetch_n_sections: 1000
    do_sample: false
    question_max_length: 128
    section_max_length: 200


indexes:
  # Defines the configuration for the multi-index
  update_freq: 5_000
  reset_model: false
  faiss:
    factory: IVF16,Flat
    nprobe: 16
    schedule:
      # progressively increase the model score weight
      type: linear
      start: 0
      end: 1
      period: 5
  bm25:
    indexed_key: text
    use_labels: true
    schedule:
      # progressively increase the model score weight
      type: linear
      start: 1
      end: 0.1
      period: 5