defaults:
  - builder: auto
  - model: default
  - resources: default
  - batch_size: default
  - trainer: default
  - monitor: retrieval
  - sys: default
  - hydra: default
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

seed: ${global_seed:}
compile: false
model_name: ${model.encoder.pretrained_model_name_or_path}
exp_name: ${builder.name}-${builder.subset_name}-${builder.language}
run_name: ${fmt_mn:${model_name}}-${rdn_name:}

loader_configs:
  # Defines the configurations for `torch.utils.data.Dataloader`
  train:
    batch_size: ${batch_size.per_device}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True

  eval:
    batch_size: ${batch_size.per_device_eval}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: True

  predict:
    batch_size: ${batch_size.per_device_predict}
    num_workers: ${resources.num_workers}
    pin_memory: True
    shuffle: False

collate_configs:
  # Defines the configurations for `dataset_builder.HfBuilder._collate_config`
  train:
    n_sections: 16
    max_pos_sections: 4
    prefetch_n_sections: 300
    do_sample: true
    question_max_length: 128
    section_max_length: 200
  eval:
    n_sections: 100
    max_pos_sections: 50
    prefetch_n_sections: 1000
    do_sample: false
    question_max_length: 128
    section_max_length: 200


# train with updates
update_freq: 1000
faiss_config:
  # Defines configuration for `FaissMaster`
  factory: IVF32,Flat
  nprobe: 16
  schedule:
    type: linear
    start: 0
    end: 1
    period: 10

bm25_config:
  # Defines configuration for `Bm25Master`
  indexed_key: section
  schedule:
    type: linear
    start: 1
    end: 0.1
    period: 10