# @package _global_

defaults:
  - override /model/encoder: bert-tiny
  - _self_

embedding_size: 64

batch_size:
  per_device: 4
  per_device_eval: 8
  per_device_predict: 10

resources:
  num_workers: 1
  num_proc: 4

trainer:
  accelerator: cpu

builder:
  n_sections:
    train: 8
    validation: null
    test: null
  subset_size: null
  question_max_length: null
  section_max_length: 220