# @package _global_

defaults:
  - override /model/encoder: bert-tiny
  - override /trainer/callbacks:
      - rich_progress_bar
  - override /trainer/logger:
      - csv
  - _self_

seed: 1

dataset:
  subset_size: 100
  filter_unused_sections: true
  train: frank.A.en-pos:train
  validation: frank.A.en-pos:val
  benchmark:
    - frank.A.en-pos:val
    - frank.B.en-pos:val

schedule:
  benchmark_on_init: false

batch_size:
  per_device: 4
  per_device_eval: 8
  per_device_predict: 10

resources:
  num_workers: 1
  num_proc: 4