# @package _global_

defaults:
  - frank-bert-base
  - override /model/encoder: t5-large
  - _self_

batch_size:
  effective: 32
  per_device: 2
  per_device_eval: 4
  per_device_predict: 1024

trainer:
  accelerator: gpu
  precision: 32