# @package _global_

defaults:
  - frank-bert-base
  - override /model/encoder: t5-large
  - _self_

model:
  embedding_size: 1024

batch_size:
  effective: 32
  per_device: 2
  per_device_eval: 4
  per_device_predict: 512

trainer:
  accelerator: gpu
  precision: 32