# @package _global_

defaults:
  - override /model/encoder: bert-base
  - override /model/gradients: kl_div
  - override /trainer/strategy: deepspeed_2
  - override /model/optimizer: adam-cpu
  - _self_


seed: 1

dataset:
  train:
    - frank.A.en-pos:train
    - squad.en:train
  validation:
    - frank.A.en-pos:val
    - squad.en:val
  benchmark:
    - frank.A.en:val
    - frank.B.en:val
    - squad.en:val


model:
  compile: true
  embedding_size: 1_024
  use_pooler_layer: false
  optimizer:
    lr: 1e-4
    weight_decay: 0
    eps: 1e-8
  scheduler:
    total_iters: 100
  gradients:
    self_supervision_weight: 0.0
    bm25_guidance_weight: 0.0

resources:
  num_workers: 4
  num_proc: 4

batch_size:
  effective: 32
  per_device: 16
  per_device_eval: 8
  per_device_predict: 2048

trainer:
  accelerator: gpu
  precision: 16-mixed
  detect_anomaly: false
  max_steps: 50_000
  limit_val_batches: 50
  val_check_interval: ${int_mul:${trainer.accumulate_grad_batches},300}


collates:
  # Defines the configurations for `dataset_builder.HfBuilder._collate_config`
  train:
    n_sections: 24
    max_pos_sections: 8
    prefetch_n_sections: 512
    do_sample: false
  benchmark:
    n_sections: 300
    max_pos_sections: 100
    prefetch_n_sections: 1000
    do_sample: false

schedule:
  index_update_freq: 1_000
  reset_model_on_period_start: false
  benchmark_on_init: true
  parameters:
    faiss:
      mode: linear
      start: 0
      value: 1
      period: 50_000

    bm25:
      mode: linear
      start: 1
      value: 0
      period: 50_000

search:
  faiss:
    factory: OPQ32,IVFauto,PQ32x8
    metric: inner_product
    nprobe: 32
    train_size: 1_000_000
  bm25:
    text_key: text
    group_key: group_hash
    persistent: true