# @package _global_

defaults:
  - msmarco-bert-base
  - override /model/encoder: t5-base
  - override /model/optimizer: adafactor
  - _self_

model:
  embedding_size: 768
  use_pooler_layer: false
  optimizer:
    lr: 1e-4
    weight_decay: 0
  scheduler:
    total_iters: 1_000


trainer:
  accelerator: gpu
  precision: 32
  limit_val_batches: 30
  val_check_interval: 300

batch_size:
  per_device: 16
  effective: 32