# @package _global_

defaults:
  - override /builder: msmarco
  - override /model/encoder: bert
  - override /model/gradients: kl_div
  - _self_

model_name: bert-base-uncased

model:
  embedding_size: null
  use_pooler_layer: true
  optimizer:
    lr: 3e-6
    weight_decay: 1e-3
  scheduler:
    total_iters: 1_000

batch_size:
  effective: 32
  per_device: 8
  per_device_eval: 64

resources:
  num_workers: 4
  num_proc: 8

trainer:
  accelerator: gpu
  precision: 16
  val_check_interval: 1_000
  limit_val_batches: 200

builder:
  top_k: 8
  subset_size: null
  question_max_length: null
  section_max_length: 200