# @package _global_

defaults:
  - override /builder: msmarco
  - override /model/encoder: bert-tiny
  - override /model/gradients: kl_div
  - _self_

model:
  embedding_size: null
  use_pooler_layer: true
  optimizer:
    lr: 1e-5
    weight_decay: 0
  scheduler:
    total_iters: 1_000

batch_size:
  effective: 64
  per_device: 64
  per_device_eval: 256

resources:
  num_workers: 4
  num_proc: 8

trainer:
  accelerator: gpu
  precision: 16
  val_check_interval: 1_000
  limit_val_batches: 200

builder:
  n_sections: 8
  subset_size: null
  question_max_length: null
  section_max_length: 200