# @package _global_

defaults:
  - override /builder: msmarco
  - override /model/encoder: bert-base
  - override /model/gradients: kl_div
  - override /batch_size: base
  - _self_

model:
  embedding_size: null
  use_pooler_layer: true
  optimizer:
    lr: 1e-5
    weight_decay: 0
  scheduler:
    total_iters: 1_000

resources:
  num_workers: 4
  num_proc: 8

trainer:
  accelerator: gpu
  precision: 16
  detect_anomaly: true
  max_steps: -1
  max_epochs: 1
  limit_val_batches: 100
  val_check_interval: 500
   #  val_check_interval: ${int_mul:${trainer.accumulate_grad_batches},500}

builder:
  n_sections:
    train: 8
    validation: null
    test: null
  subset_size: null
  question_max_length: null
  section_max_length: 220