# @package _global_

defaults:
  - override /model/encoder: t5-base
  - _self_

embedding_size: 768

model:
  optimizer:
    lr: 2e-5
    weight_decay: 1e-3

batch_size:
  per_device: 4
  per_device_eval: 32

resources:
  num_workers: 4
  num_proc: 8

trainer:
  accelerator: gpu
  precision: 16

builder:
  top_k: 8
  subset_size: null