# @package _global_

dataset:
  # Base search
  search:
    engines:
      dense:
        backend: qdrant
      sparse:
        backend: elasticsearch

  # Train/val splits
  training:
    queries:
      train:
        - identifier: frank_a_en_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
            kb_ids: [14, 156]
          subsets: en
          split: train
          link: frank_a_sections
      val:
        - identifier: frank_a_en_val
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
            kb_ids: [14, 156]
          subsets: en
          split: validation
          link: frank_a_sections

    sections:
      sections:
        - identifier: frank_a_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
            kb_ids: [14, 156]
          subsets: en

  # Benchmarks
  benchmark:
    - queries:
        identifier: frank_a_en_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: queries
          kb_ids: [14, 156]
        subsets: en
        split: train
        link: frank_a_sections
      sections:
        identifier: frank_a_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: sections
          kb_ids: [14, 156]
        subsets: en
