# @package _global_

dataset:
  # Base search
  search:
    engines:
      dense:
        backend: qdrant
      sparse:
        backend: elasticsearch

  # Train/val splits
  training:
    queries:
      train:
        - identifier: frank_a_en_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: en
          split: train
          link: frank_a_sections
        - identifier: squad_en_train
          name_or_path: squad_v2
          split: train
          options:
            set_language: en
            convert_subset_ids_to_targets: True
      val:
        - identifier: frank_a_en_val
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: en
          split: validation
          link: frank_a_sections

    sections:
      sections:
        - identifier: frank_a_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: en
          split: validation
        - identifier: squad_en_sections
          name_or_path: squad_v2
          options:
            set_language: en

  # Benchmarks
  benchmark:
    - queries:
        identifier: frank_a_en_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: queries
        subsets: en
        split: train
        link: frank_a_sections
      sections:
        identifier: frank_a_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: sections
        subsets: en
        split: validation
    - queries:
        identifier: frank_b_en_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: en
        split: train
        link: frank_b_sections
      sections:
        identifier: frank_b_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: en
        split: validation
