# @package _global_

dataset:
  # Base search
  search:
    engines:
      dense:
        backend: qdrant
      sparse:
        backend: elasticsearch

  # Train/val splits
  training:
    queries:
      train:
        # Franks
        - identifier: frank_a_en_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: en
          split: train
          link: frank_a_en_sections
        - identifier: frank_a_da_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: da
          split: train
          link: frank_a_da_sections
        - identifier: frank_a_de_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: de
          split: train
          link: frank_a_de_sections
        - identifier: frank_a_nl_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: nl
          split: train
          link: frank_a_nl_sections
        - identifier: frank_a_fr_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: fr
          split: train
          link: frank_a_fr_sections
        - identifier: frank_a_is_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: is
          split: train
          link: frank_a_is_sections
        # SQuADs
        - identifier: squad_en_train
          name_or_path: squad_v2
          split: train
        - identifier: squad_fr_train
          name_or_path: qwant/squad_fr
          split: train
        - identifier: squad_de_train
          name_or_path: deepset/germanquad
          split: train
        - identifier: squad_nl_train
          name_or_path: yhavinga/squad_v2_dutch
          split: train

      val:
        # Franks
        - identifier: frank_a_en_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: en
          split: validation
          link: frank_a_sections
        - identifier: frank_a_da_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: da
          split: validation
          link: frank_a_sections
        - identifier: frank_a_de_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: de
          split: validation
          link: frank_a_sections
        - identifier: frank_a_nl_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: nl
          split: validation
          link: frank_a_sections
        - identifier: frank_a_fr_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: fr
          split: validation
          link: frank_a_sections
        - identifier: frank_a_is_train
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: queries
          subsets: is
          split: validation
          link: frank_a_sections

    sections:
      sections:
        # Franks
        - identifier: frank_a_en_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: en
        - identifier: frank_a_da_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: da
        - identifier: frank_a_de_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: de
        - identifier: frank_a_nl_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: nl
        - identifier: frank_a_fr_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: fr
        - identifier: frank_a_is_sections
          name_or_path:
            _target_: vod_datasets.FrankDatasetLoader
            frank_split: A
            what: sections
          subsets: is
        # SQuADs
        - identifier: squad_en_sections
          name_or_path: squad_v2
        - identifier: squad_fr_sections
          name_or_path: qwant/squad_fr
        - identifier: squad_de_sections
          name_or_path: deepset/germanquad
        - identifier: squad_nl_sections
          name_or_path: yhavinga/squad_v2_dutch

  # Benchmarks
  benchmark:
    # Frank A en
    - queries:
        identifier: frank_a_en_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: queries
        subsets: en
        split: validation
        link: frank_a_en_sections
      sections:
        identifier: frank_a_en_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: A
          what: sections
        subsets: en
    # Frank B en
    - queries:
        identifier: frank_b_en_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: en
        split: train
        link: frank_b_en_sections
      sections:
        identifier: frank_b_en_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: en
    # Frank B fr
    - queries:
        identifier: frank_b_fr_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: fr
        split: train
        link: frank_b_fr_sections
      sections:
        identifier: frank_b_fr_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: fr
    # Frank B de
    - queries:
        identifier: frank_b_de_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: de
        split: train
        link: frank_b_de_sections
      sections:
        identifier: frank_b_de_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: de
    # Frank B nl
    - queries:
        identifier: frank_b_nl_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: nl
        split: train
        link: frank_b_nl_sections
      sections:
        identifier: frank_b_nl_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: nl
    # Frank B da
    - queries:
        identifier: frank_b_da_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: da
        split: train
        link: frank_b_da_sections
      sections:
        identifier: frank_b_da_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: da
    # Frank B is
    - queries:
        identifier: frank_b_is_train
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: queries
        subsets: is
        split: train
        link: frank_b_is_sections
      sections:
        identifier: frank_b_is_sections
        name_or_path:
          _target_: vod_datasets.FrankDatasetLoader
          frank_split: B
          what: sections
        subsets: is
