_target_: raffle_ds_research.core.config.TrainerConfig
max_steps: 1_000_000
val_check_interval: 500
period: 3000
gradient_clip_val: 1.0
benchmark_on_init: false
n_max_eval: null
n_max_benchmark: null
parameters:
  faiss: 1.0
  bm25: 1.0