defaults:
  - tokenizer: default
  - templates: default
  - _self_

_target_: raffle_ds_research.core.config.MultiDatasetFactoryConfig

# dataset groups
train: frank.A.en-pos:train
validation: frank.A.en-pos:val
benchmark:
  - frank.A.en:val
  - frank.B.en:val
  - squad.en:val

# benchmark config
metrics: [ "ndcg", "mrr@10","hitrate@01", "hitrate@03", "hitrate@20", "hitrate@100" , "recall@50"]

# dataset factory config
subset_size: null
filter_unused_sections: false
min_section_tokens: null

prep_map_kwargs:
  num_proc: ${resources.num_proc}