defaults:
  - tokenizer: default
  - templates: ${infer_model_type:${model/encoder}}
  - _self_

_target_: raffle_ds_research.core.config.MultiDatasetFactoryConfig

# dataset groups
train: frank.A.en-pos:train
validation: frank.A.en-pos:val
benchmark:
  - frank.A.en:val
  - frank.B.en:val
  - squad.en:val

# benchmark config
metrics: [ "ndcg", "mrr","hitrate@01", "hitrate@03", "hitrate@10", "hitrate@30" ]

# dataset factory config
subset_size: null
filter_unused_sections: false
prep_map_kwargs:
  num_proc: ${resources.num_proc}