_target_: vod_configs.TrainerConfig
max_steps: 1_000_000
val_check_interval: 500
log_interval: 10
period: 3000
gradient_clip_val: 1.0
n_max_eval: null
checkpoint_path: ${abs_path:state.ckpt}
pbar_keys: ['loss']
parameters:
  faiss: 1.0
  bm25: 1.0